#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import time
import struct
import numpy as np
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import PointCloud2
import subprocess
from datetime import datetime, timedelta
import transforms3d as tf3d
from nav_msgs.msg import Odometry
import math
import argparse
import json

# Command Line Arguments
def parse_arguments():
    parser = argparse.ArgumentParser(description='ROS navigation path processor (haptics handled by local_cam_final_haptic.py)')
    parser.add_argument('--num-pp', type=int, default=30,
                       help='Number of future path points to process')
    return parser.parse_args()

ARGS = parse_arguments()

print("[BUZZ_CAM_HAPTIC] NOTE: Haptic signals are handled by local_cam_final_haptic.py")
print("[BUZZ_CAM_HAPTIC] This script processes ROS navigation topics and exports paths")

# Global Variables
BASE_OUTPUT_DIR = "/home/unitree/buzz_out"
NUM_PP = ARGS.num_pp
ITERATION = 0
LOCAL_IP = "192.168.123.222"
LOCAL_USER = "halab2"
REMOTE_BASE = "/home/halab2/buzz_shared"

def transfer_to_local(file_path, file_type="general"):
    """Transfer file from robot to local machine using SCP"""
    try:
        # Map file types to remote directories
        dir_map = {
            "path": "path_files",
        }
        remote_dir = dir_map.get(file_type, "")

        # Always transfer to local machine (robot → local)
        # File is on robot at BASE_OUTPUT_DIR, needs to go to local at REMOTE_BASE
        remote_path = f"{LOCAL_USER}@{LOCAL_IP}:{REMOTE_BASE}/{remote_dir}/"

        print(f"[SCP] Transferring {os.path.basename(file_path)} from robot to {remote_path}")

        # Transfer the file
        result = subprocess.run(
            ['scp', file_path, remote_path],
            capture_output=True,
            text=True,
            timeout=30
        )

        if result.returncode == 0:
            print(f"[SCP] ✅ Transferred: {os.path.basename(file_path)} → {REMOTE_BASE}/{remote_dir}/")
            return True
        else:
            print(f"[SCP] ❌ Transfer failed: {result.stderr}")
            return False

    except subprocess.TimeoutExpired:
        print(f"[SCP] ⏱️ Transfer timeout for {os.path.basename(file_path)}")
        return False
    except Exception as e:
        print(f"[SCP] ❌ Exception: {e}")
        return False


class Global_Path(Node):
    def __init__(self):
        super().__init__('Global_Path')
        self.pose_subscription = self.create_subscription(
            Odometry,
            '/uslam/localization/odom',
            self.pose_callback,
            10
        )

        self.path_subscription = self.create_subscription(
            PointCloud2,
            '/uslam/navigation/global_path',
            self.path_callback,
            10
        )
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.last_processing_time = 0
        self.processing_interval = 5.0
        self.latest_msg = None
        self.message_count = 0
        self.og_yaw = None
        # NOTE: Only export FULL_PATH.txt - Path.txt is generated by robot_ui_v2.py
        os.makedirs(BASE_OUTPUT_DIR, exist_ok=True)
        self.all_paths_file = os.path.join(BASE_OUTPUT_DIR, f"All_Paths_{ts}.txt")
        self.raw_path_file = os.path.join(BASE_OUTPUT_DIR, f"Raw_Path_{ts}.txt")
        self.full_path_file = None  # Will be created on first path message

        # Robot position tracking for path processing
        self.current_waypoint_idx = 0  # Robot's position in the path
        self.current_position = None  # (x, y) from odometry
        self.initial_position = None  # Starting position for distance calculation
        self.local_odom_file = "/home/unitree/robot_odom.json"  # Write locally on robot
        self.last_transfer_time = 0  # Track last SCP transfer
        self.transfer_interval = 0.5  # seconds (transfer every 0.5s for smooth updates)

        # NOTE: Haptic signals are handled by local_cam_final_haptic.py
        # This script only processes ROS navigation topics and exports paths

        self.get_logger().info(f"Waiting for Path...{self.processing_interval}")

    # NOTE: Removed write_to_file() - buzz_cam_haptic.py only exports FULL_PATH.txt
    # Path.txt is generated by robot_ui_v2.py from the full path analysis
    
    def append_path(self, filename, text):
        """Write text to both console and file"""
        with open(filename, "a") as f:
            f.write(text)
            f.flush()

    def pose_callback(self, msg):
        o = msg.pose.pose.orientation
        quaternion = [o.w, o.x, o.y, o.z]
        euler = tf3d.euler.quat2euler(quaternion, 'szyx')
        yaw = euler[0]
        self.og_yaw = yaw

        # Extract robot's current position
        p = msg.pose.pose.position
        self.current_position = (p.x, p.y)

        # Store initial position on first message
        if self.initial_position is None:
            self.initial_position = (p.x, p.y)
            print(f"[ODOM] Initial position set: {self.initial_position}")

        # Write current odometry to local file on robot
        try:
            odom_data = {
                'x': p.x,
                'y': p.y,
                'yaw': yaw,
                'initial_x': self.initial_position[0],
                'initial_y': self.initial_position[1],
                'timestamp': datetime.now().isoformat()
            }
            with open(self.local_odom_file, 'w') as f:
                json.dump(odom_data, f)
        except Exception as e:
            self.get_logger().error(f"Failed to write odometry file: {e}")

        # Periodically transfer odometry to local machine via SCP (every 0.5s)
        current_time = time.time()
        if current_time - self.last_transfer_time >= self.transfer_interval:
            try:
                transfer_to_local(self.local_odom_file, "path")
                self.last_transfer_time = current_time
            except Exception as e:
                self.get_logger().error(f"Failed to transfer odometry: {e}")

        # Find closest waypoint (if we have path data)
        if hasattr(self, '_latest_waypoints') and self._latest_waypoints:
            min_dist = float('inf')
            closest_idx = 0
            for idx, (wx, wy, _) in enumerate(self._latest_waypoints):
                dist = math.sqrt((p.x - wx)**2 + (p.y - wy)**2)
                if dist < min_dist:
                    min_dist = dist
                    closest_idx = idx
            self.current_waypoint_idx = closest_idx


    def path_callback(self, msg):
        current_time = time.time()
        self.latest_msg = msg
        self.message_count += 1
        output_lines = []
        print(f"\n=== Global Navigation Path Message #{self.message_count} ===")
        print(f"Timestamp: {self.rostime2strf(msg.header.stamp.sec, msg.header.stamp.nanosec)}")
        print(f"Frame ID: {msg.header.frame_id}")
        print(f"Path points: {msg.width}")
        print(f"Original Yaw: {self.og_yaw:.2f}")

        # CREATE FULL PATH FILE ON FIRST MESSAGE (overwrite each time)
        if self.message_count == 1:
            print("\n[PATH] INITIAL PATH RECEIVED - CREATING FULL_PATH FILE")

            # Use single filename that gets overwritten each time
            self.full_path_file = os.path.join(BASE_OUTPUT_DIR, "FULL_PATH.txt")

            # Extract complete path coordinates
            ts_now = datetime.now().strftime("%Y%m%d_%H%M%S")
            full_path_content = f"FULL PATH FROM START TO DESTINATION\n"
            full_path_content += f"Created: {ts_now}\n"
            full_path_content += f"Total Points: {msg.width}\n"
            full_path_content += f"Frame ID: {msg.header.frame_id}\n\n"
            full_path_content += "PATH COORDINATES:\n"
            full_path_content += "─" * 50 + "\n"

            # First, extract all waypoint coordinates from PointCloud2
            waypoints = []
            for i in range(msg.width):
                offset = i * msg.point_step
                try:
                    x = struct.unpack('f', msg.data[offset:offset+4])[0]
                    y = struct.unpack('f', msg.data[offset+4:offset+8])[0]
                    waypoints.append((x, y))
                except Exception as e:
                    print(f"Error extracting point {i}: {e}")

            # Calculate heading for each waypoint based on direction to next waypoint
            for i in range(len(waypoints)):
                x, y = waypoints[i]

                # Calculate heading: direction to NEXT waypoint (compass-style heading)
                if i < len(waypoints) - 1:
                    x_next, y_next = waypoints[i + 1]
                    dx = x_next - x
                    dy = y_next - y
                    # Compass-style heading: atan2(dx, dy) where 0°=North(+y), 90°=East(+x), clockwise
                    heading_rad = math.atan2(dx, dy)
                    heading_deg = math.degrees(heading_rad)
                    # Normalize to -180 to 180 range
                    while heading_deg > 180:
                        heading_deg -= 360
                    while heading_deg < -180:
                        heading_deg += 360
                else:
                    # For last waypoint, use heading to previous waypoint
                    if i > 0:
                        x_prev, y_prev = waypoints[i - 1]
                        dx = x - x_prev
                        dy = y - y_prev
                        heading_rad = math.atan2(dx, dy)
                        heading_deg = math.degrees(heading_rad)
                        while heading_deg > 180:
                            heading_deg -= 360
                        while heading_deg < -180:
                            heading_deg += 360
                    else:
                        heading_deg = 0.0

                line = f"Point {i:2d}: ({x:7.3f}, {y:7.3f}) | Heading: {heading_deg:6.1f}°\n"
                full_path_content += line
                if i < 5:  # Only print first 5 points with debug info
                    print(line.strip())
                    if i < len(waypoints) - 1:
                        print(f"       [DEBUG] dx={dx:.3f}, dy={dy:.3f}, atan2={math.degrees(math.atan2(dy, dx)):.1f}°, converted={heading_deg:.1f}°")

            # Save full path file immediately
            try:
                with open(self.full_path_file, 'w') as f:
                    f.write(full_path_content)
                os.sync()
                file_size = os.path.getsize(self.full_path_file)
                print(f"\n[PATH] ✅ FULL_PATH file created: {self.full_path_file} ({file_size} bytes)")
                transfer_to_local(self.full_path_file, "path")
            except Exception as e:
                print(f"[PATH] ❌ Error creating full path file: {e}")

        if current_time - self.last_processing_time >= self.processing_interval:
            self.last_processing_time = current_time
            self.print_path_coordinates(msg)
            # Extract and print the actual path coordinates
            coordinates_output = self.manual_decode_points(msg)
            output_lines.extend(coordinates_output)
            output_lines.append("=" * 50 + "\n")
    
    def normalize_angle(self, angle):
        while angle > math.pi:
            angle -= 2 * math.pi
        while angle < -math.pi:
            angle += 2 * math.pi
        return angle

    def print_path_coordinates(self, msg):
        """Extract and print the x,y,z coordinates from PointCloud2 data"""
        if msg.width == 0:
            print("No points in path")
            return []
        
        print("\nPath Coordinates (x, y):")
        print("-" * 30)
        
        return self.manual_decode_points(msg)

    def manual_decode_points(self, msg):
        # string array for x,y data
        output_lines = []
        
        # data array for x, y
        data_list = []
        append_path = []
        global ITERATION
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Process ALL waypoints (not limited to NUM_PP)
        for i in range(msg.width):
            offset = i * msg.point_step
            # extract x (bytes 0-3)
            x = struct.unpack('f', msg.data[offset:offset+4])[0]
            # extract y (bytes 4-7)
            y = struct.unpack('f', msg.data[offset+4:offset+8])[0]

            line = f"Point {i:2d}: ({x:7.3f}, {y:7.3f})"
            print(line)

            data_list.append([x, y, self.og_yaw])
            output_lines.append(line + "\n")

        # NOTE: Path.txt is no longer generated here
        # It will be generated by robot_ui_v2.py from FULL_PATH.txt analysis
        try:
            # Log raw path data for reference
            self.append_path(self.all_paths_file, f"USLAM Navigation Path - {ts}, {msg.width} waypoints\n")
            self.append_path(self.raw_path_file, f"USLAM Path Log - Started at {ts}, Iteration {ITERATION}\nWaypoints: {msg.width}\n\n")

        except Exception as e:
            print(f"[PATH] Error logging: {e}")

        # Transfer log files to local
        self.append_path(self.all_paths_file, "".join(output_lines) + "\n\n")
        os.sync()
        time.sleep(0.1)
        transfer_to_local(self.all_paths_file, "path")
        transfer_to_local(self.raw_path_file, "path")
        ITERATION += 1
        return output_lines

    def step(self, prev, current, current_yaw, threshold=0.05):
        prev_move = "forward"
        dx = current[0] - prev[0]
        dy = current[1] - prev[1]
        print(f"DX:{dx}, DY:{dy}")
        segment_yaw = math.atan2(dy, dx)
        turn_angle_rad = self.normalize_angle(segment_yaw - current_yaw)
        turn_angle_deg = math.degrees(turn_angle_rad)
        # check forward
        if turn_angle_deg < 15 or dx == 0 or dy == 0:
            prev_move = "forward"
            return "forward"
        # check turn
        elif turn_angle_deg > 0:
            prev_move = "turn left"
            return  "turn left"
        elif turn_angle_deg < 0:
            prev_move = "turn right"
            return "turn right"
        else:
            return f"continue {prev_move}"

    def rostime2strf(self, ros_sec, ros_nano):
        sec = ros_sec + (ros_nano * 1e-9)
        dt = datetime.fromtimestamp(sec)
        return dt.strftime('%Y%m%d_%H%M%S')
        
    def translate_nl(self, data_list, msg, window_size=3, speed=0.25):
        movements = []
        ts = self.rostime2strf(msg.header.stamp.sec, msg.header.stamp.nanosec)
        ts_converted = datetime.now()

        if len(data_list) < window_size:
            movements.append("Path not long enough")
            return []

        smooth_data = []
        for i in range(len(data_list)):
            start = max(0, i - window_size//2)
            end = min(len(data_list), i + window_size//2 + 1)
            window = data_list[start:end]
            avg_x = np.mean([p[0] for p in window])
            avg_y = np.mean([p[1] for p in window])
            smooth_data.append((avg_x, avg_y, 0))

        # Store waypoints for lookahead calculation
        self._latest_waypoints = smooth_data

        current_yaw = self.og_yaw

        for i in range(1, len(smooth_data)):
            movement = self.step(smooth_data[i - 1], smooth_data[i], current_yaw)
            if movement:
                print("[PATH] Detected movement at waypoint {}: {}".format(i, movement))

                # Calculate distance from current robot position to this waypoint
                if self.current_position:
                    dist_to_waypoint = math.sqrt(
                        (smooth_data[i][0] - self.current_position[0])**2 +
                        (smooth_data[i][1] - self.current_position[1])**2
                    )
                else:
                    dist_to_waypoint = float('inf')  # No odometry yet

                # Log path information (haptics handled by local_cam_final_haptic.py)
                print("[PATH] {} at waypoint {} ({:.1f}m away)".format(movement, i, dist_to_waypoint))

                dx = smooth_data[i][0] - smooth_data[i-1][0]
                dy = smooth_data[i][1] - smooth_data[i-1][1]
                distance = np.sqrt(dx**2 + dy**2)
                t = distance / speed
                ts_converted += timedelta(seconds=t)
                ts = ts_converted.strftime('%Y%m%d_%H%M%S')
                movements.append("command: {}, time: {}".format(movement, ts))
            else:
                movements.append("command: None, time: None")

        return movements
    
    def __del__(self):
        if hasattr(self, 'output_file') and self.output_file:
            self.output_file.close()

def main():
    rclpy.init()
    node = Global_Path()
    
    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.1)
    except KeyboardInterrupt:
        print("\nShutting down...")
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == "__main__":
    main()
